### ISSUE TITLE
Which classifier did you use?

### ISSUE THREAD

**Issue by parthdhameliya** [sainimohit23/FaceNet-with-TripletLoss#4]
Hii,
I would like to know that after training triplet loss, for face recognition in Webcam script which classifier do you use?

**Comment by sainimohit23** [comment]
I have not used any classifier. There is this [function](https://github.com/sainimohit23/FaceNet-Real-Time-face-recognition/blob/71277f34bd5fa43fbddb1c4c5051fb3d3f029ae4/webcamFaceRecoMulti.py#L68) in webcam script which uses model to generate encodings for webcam feed. Then these encodings are matched with the encodings of images present in our database. 


Refer this notebook to understand it: https://github.com/gemaatienza/Deep-Learning-Coursera/blob/master/4.%20Convolutional%20Neural%20Networks/Face%20Recognition%20for%20the%20Happy%20House%20-%20v3.ipynb

Also watch this video: https://www.youtube.com/watch?v=0NSLgoEtdnw&list=PLkDaE6sCZn6Gl29AoE31iwdVwSG-KnDzF&index=36

**Comment by parthdhameliya** [comment]
okay now got it. Thank you for your explanation. 
Can you please tell me that if I train my model on triplet loss and then i want to classify faces using softmax classifier is this possible?
if yes then can you please tell me how can I implement that?

**Comment by sainimohit23** [comment]
You can try to add extra softmax layer as output layer and train it by freezing previous layers. But, to train softmax layer you must have a lot of image data for training.
