### ISSUE TITLE
Training fail

### ISSUE THREAD

**Issue by ani16** [sainimohit23/FaceNet-with-TripletLoss#6]
Hi

Training fails with train_triplet.py. It throws error -

 np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train_triplet.py", line 43, in <module>
    if os.path.exists(best_model_path):
NameError: name 'best_model_path' is not defined

Kindly do help me.

**Comment by davidchong** [comment]
hi, i guess you have to download a .h5 model and update the link link the train_triplet.py 
I am working on it currently as well. good luck
