### ISSUE TITLE
Testing fail

### ISSUE THREAD

**Issue by ani16** [sainimohit23/FaceNet-with-TripletLoss#7]
Hi Mohit.

Used updated repo and it work. But my problem is when I trained the Model, checkpoint directory is created and weights are saved. But when I test the Model with command- “python webcamFaceRecoMulti.py”. It shows error-

Using TensorFlow backend.
Trained model found
Loading custom trained model…
2019–08–13 11:02:30.007665: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/root/env/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
 warnings.warn(‘No training configuration found in save file: ‘
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
VIDEOIO ERROR: V4L: can’t open camera by index 0
Traceback (most recent call last):
 File “webcamFaceRecoMulti.py”, line 103, in <module>
 frame = imutils.resize(frame, width = 800)
 File “/root/env/lib/python3.6/site-packages/imutils/convenience.py”, line 69, in resize
 (h, w) = image.shape[:2]
AttributeError: ‘NoneType’ object has no attribute ‘shape’

Screenshot is attached.

**Comment by balajib363** [comment]
@ani16 check for images know!
I am working using the same script and I am not facing any issue.

**Comment by balajib363** [comment]
@sainimohit23 when running webcamFaceRecoMulti.py it's not drawing the results appropriately.
can you please share an update on that same?

**Comment by sainimohit23** [comment]
@BalajiB197 Program uses "Haar Cascade" algorithm to detect face coordinates. Check this line of code: " https://github.com/sainimohit23/FaceNet-Real-Time-face-recognition/blob/bf1357d040511e8aba8d306596fa97f7e5bab0c9/webcamFaceRecoMulti.py#L96 ". If you know any better algorithm then try to use it with this code.

**Comment by sainimohit23** [comment]
@ani16 It seems like it has something to do with openCV in this line of code: https://github.com/sainimohit23/FaceNet-Real-Time-face-recognition/blob/bf1357d040511e8aba8d306596fa97f7e5bab0c9/webcamFaceRecoMulti.py#L95

Here `0` means we want to access webcam. But, in your case somehow program is not retrieving any image frame from webcam. That's why it is returning `None`.

**Comment by ani16** [comment]
@Mohit , Balaji

Thanks for reply. 

Sorry I dont have webcam right now. Is there any facility to run with offline videos(saved on system) or offline images.. what changes I need to make in codes.

Moreover I am trying with given images in Repo like Henry and Ben. Once It get tested successfully, I will train with my own dataset and test it.

**Comment by balajib363** [comment]
@ani16 you can pass any video file path as input to your program.
just replace 0 with **'video path'** or **'RTSP link'**

**Comment by ani16** [comment]
Thanks for reply.  This change(video path)  is required at one place
only.?

**Comment by ani16** [comment]
One thing More,  I trained Repo with given set of images, Henry and Ben. checkpoint directory is created. I want to test with that very images of Henry and Ben. Should I need to add image path instead of video path. At this place- '' just replace 0 with 'video path' or 'RTSP link' " ?

**Comment by ani16** [comment]
@Mohit, Balaji

I have placed video path in VideoCapture(0) but still Attribute error is there.

Using TensorFlow backend.
Custom trained model not found, Loading original facenet model...
2019-08-16 13:17:08.144699: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
(1, 3, 96, 96)
Traceback (most recent call last):
  File "webcamFaceRecoMulti.py", line 103, in <module>
    frame = imutils.resize(frame, width = 800)
  File "/root/env/lib/python3.6/site-packages/imutils/convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Please guide me how to resolve this. Thanks

**Comment by ani16** [comment]
Hey it works with video path. But it fails to detect and classify images. why this is so. I used pretrained model of FaceNet and performed detection on video of Ben (taking his images from cropped folder and created a short video) to test the model. But it fails and throws error - 

henry : 0.67537445 3
(1, 3, 96, 96)
ben : 0.82383454 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.66721743 3
(1, 3, 96, 96)
ben : 0.8079582 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.69378686 3
(1, 3, 96, 96)
ben : 0.84412855 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.6789233 3
(1, 3, 96, 96)
ben : 0.8292798 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.69600886 3
(1, 3, 96, 96)
ben : 0.84772164 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.6944892 3
(1, 3, 96, 96)
ben : 0.85749876 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.6949351 3
(1, 3, 96, 96)
ben : 0.8556409 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.70652777 3
(1, 3, 96, 96)
ben : 0.84497267 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.7110802 3
(1, 3, 96, 96)
ben : 0.8468099 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.7001207 3
(1, 3, 96, 96)
ben : 0.8070818 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.72043705 3
(1, 3, 96, 96)
ben : 0.78296345 3
(450, 800, 3)
(1, 3, 96, 96)
henry : 0.6969753 3
(1, 3, 96, 96)
ben : 0.7893841 3
Traceback (most recent call last):
  File "webcamFaceRecoMulti.py", line 103, in <module>
    frame = imutils.resize(frame, width = 800)
  File "/root/env/lib/python3.6/site-packages/imutils/convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

please guide me.

**Comment by ani16** [comment]
Hi

I tried with video, I gives poor result. Not recognising persons properly
and infact I changed  epochs to 50,it still stops at 6-10 epochs while
training . Why is it so
