### ISSUE TITLE
training fail

### ISSUE THREAD

**Issue by dipesh-adekar** [sainimohit23/FaceNet-with-TripletLoss#9]
training fails while running triplet_loss.py with throwing error:
ValueError: Cannot feed value of shape (64, 2, 1) for Tensor 'FaceRecoModel_target:0', which has shape '(?, ?)'

**Comment by priyanshthakore** [comment]
Hi 
Great post on medium,
but i am also facing the same issue as @dipesh-adekar,
did you ever run into this issue or do you know why this might be happening.

**Comment by ani16** [comment]
Hi

I don't face any issue in training. It works well and generates weights in checkpoint directory.
